services:
  ojs:
    image: pkpofficial/ojs:3_4_0-5
    container_name: ojs
    restart: unless-stopped
    user: root                 # <--- YE HAI JAADUI LINE (Permission error fix karegi)
    depends_on:
      - mysql
    environment:
      SERVERNAME: ijaml.com
      HTTPS: 'on'
      OJS_DB_HOST: mysql
      OJS_DB_USER: Admin
      OJS_DB_PASSWORD: Project@1
      OJS_DB_NAME: ojs
      OJS_DB_DRIVER: mysqli
    ports:
      - '8081:80'
    volumes:
      - ojs-public-v4:/var/www/html/public
      - ojs-private-v4:/var/www/files
      - ./config.inc.php:/var/www/html/config.inc.php
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.ijaml-ojs-nptusz-60-web.rule=Host(`ijaml.com`)
      - traefik.http.routers.ijaml-ojs-nptusz-60-web.entrypoints=web
      - traefik.http.routers.ijaml-ojs-nptusz-60-web.middlewares=redirect-to-https@file
      - traefik.http.routers.ijaml-ojs-nptusz-60-websecure.rule=Host(`ijaml.com`)
      - traefik.http.routers.ijaml-ojs-nptusz-60-websecure.entrypoints=websecure
      - traefik.http.routers.ijaml-ojs-nptusz-60-websecure.tls.certresolver=letsencrypt
    networks:
      - dokploy-network

  mysql:
    image: mariadb:10.5
    container_name: ojs-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Project@1
      MYSQL_DATABASE: ojs
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Project@1
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    volumes:
      - db_data-v4:/var/lib/mysql
    networks:
      - dokploy-network

volumes:
  ojs-public-v4:
  ojs-private-v4:
  db_data-v4:

networks:
  dokploy-network:
    external: true
